services:
  bot:
    container_name: bot
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - "${BOT_PORT}:8000"
    volumes:
      - ../:/ecommerce-telegram-bot
    command: [ "./entrypoint.sh" ]
    restart: always
